kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zeebe-regional
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd
#   replication-type: regional-pd
#   zones: "{{region_zones}}"
reclaimPolicy: Retain
